### ISSUE TITLE
Own events are missing

### ISSUE THREAD

**Issue by crecca** [simonbengtsson/eventcal#10]
Using your service for months, and it's very helpful. Today I realized, that the events organized by me are not showing up in my google calendar (more than a day had passed). Other events are fine. Any ideas, similar problems?

**Comment by crecca** [comment]
Somehow they finally appeared. (I don't know if you had updated sg. in the meantime.) Some 36 hours later, but still, I usually need my calendar to be more up to date. I'll keep an eye on it anyway.

**Comment by simonbengtsson** [comment]
The service updates every time google calendar tries to fetch a new version of the calendar. I have noticed that this sometimes takes some time, but should normally happen within a few hours. I don't know of a way to manually refresh a google calendar other then removing it and readding it.
