### ISSUE TITLE
Refresh rate on your hosted service?

### ISSUE THREAD

**Issue by ckrf** [simonbengtsson/eventcal#13]
First--huge thanks! This is a super useful project. It has really saved me a bunch of times.

Do you know that it takes a while (maybe 12-24 hours) for a newly selected event to appear in one's calendar feed? Is this unavoidable without greatly increasing the server load required?

**Comment by simonbengtsson** [comment]
Thanks! It is the same refresh rate as your calendar software. This can be set to instant on most local calendars while google calendar takes a few hours.
