### ISSUE TITLE
calendar names lost in google calendar app on iphone

### ISSUE THREAD

**Issue by chrispitzer** [simonbengtsson/eventcal#14]
I've created a few calendars with this tool. Put them in Google Calendar, and they show up in the google calendar web app just fine. But when I look at them on my phone through the iphone google calendar phone app, the name of each calendar is "[some arabic looking characters] my name [some more arabic looking characters]"

I'm wondering if there's some metadata that the google calendar web app is looking at that isn't being properly configured?

The rest of the data in the calendar is totally fine.

**Comment by simonbengtsson** [comment]
Fixed in 4c0bb10ff06, thanks for reporting. Facebook seems to think my server is located in an arabic speaking country for some reason.
