### ISSUE TITLE
Events being translated into spanish

### ISSUE THREAD

**Issue by dmyers** [simonbengtsson/eventcal#15]
I'm not sure why though, but they are in Spanish my calendar, but all of my settings in FB under language are set to English.

**Comment by simonbengtsson** [comment]
Strange! I'll look into it.

**Comment by simonbengtsson** [comment]
I looked into it now and can't replicate the issue. What parts of events are translated into Spanish?

**Comment by dmyers** [comment]
Oops I meant to mention too that I used the birthday event feed and it happened. When I went back and got my upcoming feed url it worked in English as expected.

**Comment by simonbengtsson** [comment]
Hmm, interesting, will try the birthday feed. Although there is no use case for using that with this service right?

**Comment by dmyers** [comment]
Actually, yeah that is a good point. I think we can attribute some to user error as I saw the word birthday and grabbed the wrong one. 😞
