### ISSUE TITLE
calendar events from facebook are not showing

### ISSUE THREAD

**Issue by esalcido** [simonbengtsson/eventcal#16]
I copied the link from my facebook events link(upcoming events) and pasted it to input box #1 on the page http://eventcal.flown.io/, clicked on google calendar button and it was added to my google calendar but nothing is being displayed from my facebook events in my calendar.  Is there any way we can fix this?

**Comment by esalcido** [comment]
I'm sorry I think I misread this service.  Is it only for iCal or Apple products? I've been testing on the Google Calendar for web as well as google calendar for Android.

**Comment by simonbengtsson** [comment]
Google Calendar is what I originally created it for but should work for any calendar software. It might take a few hours for initial sync to take place, is it still not working?

**Comment by esalcido** [comment]
Ah ok, now its working. It took a good 4 hours but its working. Thank you! This service is cool 👍
