### ISSUE TITLE
improvements needed

### ISSUE THREAD

**Issue by nolybom** [simonbengtsson/eventcal#17]
Aloha,
quite happy that i found your script here. Thank you!
I was actually dealing with some other scripts but yours seams quite reliable.
Discovered a small bug though.

Button of the System Calendar should'nt open a new tab, so in line 119 you could do this:

`window.open(url,"_self");`

Then in line 149 we have:

`var base = 'webcal://' + window.location.host + '?base64=true&calendar=';`

Unfortunately that restricts eventcal to the root. If eventcal is placed in a directory the generated webcal-link is invalid.

Do you have an idea how we could integrate events of a public fanpage and limit it it to get only upcoming events?
The Graph would look like this:

`https://graph.facebook.com/v2.9/17168992485/events?time_filter=upcoming&access_token=xxxyyyzzz`

Of course a access_token is needed.

**Comment by nolybom** [comment]
Another idea would be to cache the .ics file(s). What do you think?

**Comment by simonbengtsson** [comment]
Sounds like great changes, feel free sending a pull request! I'm not very familiar with the graph api so can't help you there I'm afraid. 

Cheers!

**Comment by simonbengtsson** [comment]
What do you mean by caching the ics file? When would that be advantageous?

**Comment by simonbengtsson** [comment]
Changed to `window.open(url, '_self')` now

**Comment by nolybom** [comment]
> What do you mean by caching the ics file? When would that be advantageous?

I meant to actually store the .ics file(s) once fetched from facebook instead of requesting the same eventinfo each time the webcal is being triggered.

I think i was comsidering in my thoughts webcals which would have been generated out of a fanpage and offered as a calendar service on a website. Depending on the amount of people subscribing the calendar ...you can imagine how many redundant requests would be made.
Hope i could explain this time a little better.

**Comment by simonbengtsson** [comment]
I'm not sure what you mean by fanpage? Do you mean a Facebook page? Is it possible to get an ical url of upcoming urls for a page in the same way it is from a profile's upcoming events?

And if the above is possible. What is the advantage of caching? To reduce the amounts of requests to the facebook servers? I think they can manage ^^

**Comment by nolybom** [comment]
Well wouldn't the server hosting your script be the first and last instance handling everything? I think so.

But let's talk about the facebook page...yes, that's what i mean.

So here is an example of a workflow:

We will take the facebook page of "The NYC Daily Event List".

To get the events data from facebooks graph all you have to do is what i have stated in my very first post (see above):

Lets say we want to get all available info from this facebook event:

https://www.facebook.com/pg/klassischephilharmoniebonn/events/

(or any other which has upcoming events listed of course)

1. create a developer account at facebook to get an app_id & app_secretcode.
2. i found that this site offers the most reliable way of getting one...scroll to the very bottom and get your access_token.
3.Get the facebook ID of the desires fb-page: https://findmyfbid.com


Now you have everything you need to receive all data of the events:

For a quick reference you can for now use my assets. Just open this:

https://graph.facebook.com/v2.9/17168992485/events?time_filter=upcoming&access_token=1652952421698132|Pi1XyrB5kVv7BVm4rbDCINEPkYk

So far so good. Now we need to get it sorted out into a format we can use for creating a ics or webcal. We can use this script for this:

https://github.com/chrisnoisel/FB-events-to-iCalendar

And from here it would be easy for you to extend your script, don't you think?

**Comment by simonbengtsson** [comment]
Aha! So in short you want a service where you can enter a facebook page and get ical url of all events that page has planned?

**Comment by simonbengtsson** [comment]
As you pointed out, you would probably need to use the graph api etc so that service would probably have very little in common in terms of code with this one. It's an interesting idea and if I ever find the need myself I might do it. Let me know if you end up implementing it.
