### ISSUE TITLE
Feature request: Show "Saved Events"

### ISSUE THREAD

**Issue by alego500** [simonbengtsson/eventcal#20]
Facebook has an option called "Saved" when checking events. Basically this is a private version of the "Interested" option. As there are no way to private that you are interested in I was wondering if this is possible to implement, preferably to the website version?

**Comment by simonbengtsson** [comment]
Looked into it now and it wouldn't be possible to add that feature without using Facebook's API. Currently this service uses a public calendar url which has the advantage of not requiring any login by users. To limit the scope of this project I won't add that. If someone comes up with a good way of implementing it I might reconsider though.
