### ISSUE TITLE
Doesn't list events you created yourself

### ISSUE THREAD

**Issue by quintrino** [simonbengtsson/eventcal#21]
Hi, 

It appears at some point they have updated the Facebook events process so that you don't have an attending/maybe attending/can't go option for your own events. This seems to stop events I've created myself from showing up in the eventcal feed. 

Not sure if you'll have time to look at it but would greatly appreciate it if you can!

**Comment by simonbengtsson** [comment]
Interesting! I fear that it is not much I can do without fundamentally altering the service, but I'll take a look at once.

**Comment by simonbengtsson** [comment]
I tried adding a private event now and it showed up in the calendar. Can you tell me a little bit more about the event that failed to show up?

**Comment by quintrino** [comment]
Hmm, sure, I made it within a private group, I made it last week and it's still not showing.  Are there other details you'd like?

**Comment by simonbengtsson** [comment]
Tried it now and got the same result ie events created in secret groups not showing up. I can't think of a way to fix it with the current architecture.

**Comment by quintrino** [comment]
Hmm, if I re internet my cal link will it create a new URL for me? or will it just provide the previous one?

**Comment by simonbengtsson** [comment]
It encodes your URL in a new URL.

**Comment by quintrino** [comment]
Okay, I deleted the old url from Google Calendar and subscribed to a new one and it seems to be working again. I'll update if it happens again but for now I'm closing the issue.

**Comment by simonbengtsson** [comment]
So it worked for you know even if the event were posted in a secret facebook group ?
