### ISSUE TITLE
Serve over HTTPS

### ISSUE THREAD

**Issue by HazCod** [simonbengtsson/eventcal#22]
First of, thank you for this service!

As plain HTTP can be intercepted and changed without any problem, it would be beneficial if we could serve this over functional HTTPS.

As eventcal.flown.io does not have the correct certificate, I suppose you are not using LetsEncrypt?
Could you put this into a herokuapp or something like that? That would provide you with automatic, valid SSL certificates.

**Comment by simonbengtsson** [comment]
Good point! Will enable letsencrypt.

**Comment by simonbengtsson** [comment]
Done

**Comment by HazCod** [comment]
Thanks!
