### ISSUE TITLE
Unchecked Going and Maybe events staying on calendar.

### ISSUE THREAD

**Issue by MedicineManOfSeattle** [simonbengtsson/eventcal#23]
When I go through and uncheck the maybe and/or going to the FB events, the events are still on my calendar. 

Duplicates also seem to be created if I recheck Maybe or Going for a series of events.

**Comment by simonbengtsson** [comment]
Strange! Probably not much that can be done in this service however since it is only a filter between the facebook and a calendar client and does not store any data. If duplicates exists it should either be the calendar client or facebook that creates them. My guess would be your calendar client since it works for me.

**Comment by MedicineManOfSeattle** [comment]
It's probably more a function of how often, if ever, the program calls for the calendar events.

I'm sure it's also the same issue with FB not being restive on the length of event names (70 characters) that is messing up their native iCal as well.

**Comment by simonbengtsson** [comment]
Whenever a calendar client want's an update it will request it by eventcal which in turn will request an update from facebook which it sends back to the calendar client slighty filtered and sanitized. The refresh frequency can vary greatly from client to client and in Apple Calendar you can specify it yourself.

Is it some calendar client only supporting 70 characters? Maybe it would be helpful to add an optional 70 character filter as well to the title then?

**Comment by simonbengtsson** [comment]
Not sure what that link says? I have not tried but I think Google Calendar supports more than 70 character titles?
