### ISSUE TITLE
Make calendar non read-only if possible

### ISSUE THREAD

**Issue by mnaoumov** [simonbengtsson/eventcal#24]
Google Calendar allows to add an attachment to the events as links to Google Drive. That's very useful for concerts, where you can add the concert ticket into the Google Drive and attach it to the event

Currently your calendar is read-only so I cannot add attachments. To workaround the issue, I clone the event and add an attachment there. But I would prefer for this workaround to be avoided

**Comment by simonbengtsson** [comment]
Interesting use case! Unfortunately I can come up with a way to do this without increasing the complexity of the service at least 10 fold as some kind of merge strategy would be needed. Currently the service just takes whatever events are on facebook and replaces the Google Calendar ones with them. Therefore I consider this out of scope unless someone can come up with a good solution.

**Comment by mnaoumov** [comment]
@simonbengtsson I would suggest keeping it one-way synchronization for all fields except attachments, taking data from Facebook. So whenever event changes in Facebook, override the event field.
Since the Facebook event doesn't have any attachment data, you can safely ignore it when merging.

**Comment by simonbengtsson** [comment]
Have not found any way to do this with current architecture
