### ISSUE TITLE
Calendar subscription error

### ISSUE THREAD

**Issue by caspercornelius** [simonbengtsson/eventcal#25]
Calendar stopped working.
"There was an unexpected error with the request on subscribed calendars (error -1)."

Please advise!

**Comment by JonMdV** [comment]
Having the same problem, help!!  

I rely on this completely to organize my life :(

**Comment by simonbengtsson** [comment]
Facebook updated their calendar urls, but should work again now!

**Comment by caspercornelius** [comment]
Thanks, Simon! Life saver! :)

**Comment by JonMdV** [comment]
Thanks for the good news...but I can't find where to get the updated URLs at least for my account.

The page I used to get them previously just disappeared...

**Comment by simonbengtsson** [comment]
This guide still works for me https://www.facebook.com/help/152652248136178

**Comment by simonbengtsson** [comment]
<img width="845" alt="screenshot 2018-11-13 at 09 13 42" src="https://user-images.githubusercontent.com/3586691/48399618-75715280-e724-11e8-94d4-3b8e12c01c53.png">

**Comment by JonMdV** [comment]
Finally working again...
Thanks for the hard work!
