### ISSUE TITLE
Max Length limitation

### ISSUE THREAD

**Issue by mustafaozhan** [simonbengtsson/eventcal#28]
Hello,

Everything is working fine while adding calendar first time but they are not syncing when i reply to new events. I searched little bit about it. The reason seems that long description of events.

if not there is a problem with syncing. I am not able to see new events in my google calendar. I can only see the events from first import time

**Comment by mustafaozhan** [comment]
Hello I am still testing it. it takes time bec of number of possible events but weirdly it sync sometimes and I couldn't understand. Maybe eventcal is syncing events between Facebook calendar to Google calendar 1-2 times in a day ?

**Comment by simonbengtsson** [comment]
That’s possible! You can think of eventcal more like a filter and doesn’t actually request anything. Whenever google calendar requests new an update eventcal requests new events from Facebook and pass them on to google calendar.

**Comment by mustafaozhan** [comment]
Hello,

Sorry It was my delay to check different situations also sorry for unrelated issue with eventcal I am closing this issue bec it is not related with eventcal and it is working well :smiley:
