### ISSUE TITLE
Facebook export not supported anymore

### ISSUE THREAD

**Issue by skjerns** [simonbengtsson/eventcal#29]
As far as I see, it is unforunately not possible anymore to subscribe to Facebook events.

Do you know any alternative how to get my upcoming events to my local calendar?

**Comment by simonbengtsson** [comment]
How do you mean not possible anymore? Seems to be working fine to go to [facebook/events](https://www.facebook.com/events/) and copy the url as before?

**Comment by skjerns** [comment]
my bad!! sorry, just the format changed

**Comment by simonbengtsson** [comment]
True! Feel free to include a more accurate guide on the homepage and send a PR!

**Comment by skjerns** [comment]
`The URL should look similar to this: webcal://www.facebook.com/ical/u.php?uid=1645531053&key=AQDdB7kP2hjd14uh`

should be changed to

`The URL should look similar to this: https://www.facebook.com/events/ical/upcoming/?uid=35463450&key=afasdtg354oDg`
