### ISSUE TITLE
Events disappeared

### ISSUE THREAD

**Issue by MatyiFKBT** [simonbengtsson/eventcal#36]
Maybe has something to do with facebook removing the method from their "support page".
https://www.facebook.com/help/152652248136178

**Comment by dahacouk** [comment]
I think you are correct. This export method is gone. RIP interoperability! :-(

**Comment by daniilS** [comment]
The export method seems to be back again, but eventcal is still broken?

**Comment by simonbengtsson** [comment]
Seems the feature is back! 🎉 

<img width="576" alt="Screen Shot 2021-04-16 at 11 28 18" src="https://user-images.githubusercontent.com/3586691/115004541-302e4d80-9ea7-11eb-98e8-8a3f59393f89.png">
