### ISSUE TITLE
No iCal-link in the new Facebook version

### ISSUE THREAD

**Issue by WhiteSasch** [simonbengtsson/eventcal#38]
Hello

There is no iCal-link in the new Facebook version. I assume that there isn't any possibility to sync Facebook events with your own Google Calendar, nowdays?

**Comment by simonbengtsson** [comment]
Seems they have added this feature back now 👌

<img width="576" alt="Screen Shot 2021-04-16 at 11 28 18" src="https://user-images.githubusercontent.com/3586691/115004440-1856c980-9ea7-11eb-8a4a-60a18276ec0b.png">
