### ISSUE TITLE
Choose filtered events

### ISSUE THREAD

**Issue by paddel102** [simonbengtsson/eventcal#4]
Would be nice to be able to choose which events should be filtered e.g. events I'm just 'interested'

**Comment by simonbengtsson** [comment]
You mean that you want a calendar with only the events you are interested in?

**Comment by paddel102** [comment]
No the other way around. Only events are shown where I am "going" but not where I am just "interested". Most perfect would be a nice GUI with checkboxes which events to export of course :D

**Comment by simonbengtsson** [comment]
Ah! Makes more sense, will see what I can do!

**Comment by paddel102** [comment]
Perfect! I'm keeping track! Thanks a lot for your work!

**Comment by simonbengtsson** [comment]
Added preliminary support now. GUI will come at another time however. If you want only events you have marked that you are attending you can add the following to your calendar url: `&status=accepted`.

The full url should then look something like this: `webcal://eventcal.flown.io/?calendar=webcal%3A%2F%2Fwww.facebook.com%2Fical%2Fu.php%3Fuid%3D1635641053%26key%3DAQDysB2kPhja14uh&status=accepted`

If you don't add anything to the url it is basically the same as `&status=accepted,tentative`. If you don't want the service to filter at all for some reason you can add all types which would look like this `&status=accepted,tentative,needs-action`.

`tentative` is for events marked as maybe or interested in
`accepted` is for events marked as going to
`needs-action` is for events not responded to

**Comment by paddel102** [comment]
Nice!

**Comment by shirazd** [comment]
This is awesome. Thanks!!!

**Comment by stas-slu** [comment]
Looks cool, can't wait :)
