### ISSUE TITLE
Event link errors out with login page

### ISSUE THREAD

**Issue by dapetcu21** [simonbengtsson/eventcal#40]
Possibly Facebook now needs its session cookie when downloading the .ical?

<img width="1440" alt="Screen Shot 2021-05-02 at 21 14 23" src="https://user-images.githubusercontent.com/428060/116823114-5fbda500-ab8b-11eb-8ef3-5fb66e035ba4.png">

**Comment by simonbengtsson** [comment]
Interesting. 

1. What did you do to get this page?
2. What web browser and operative system?

**Comment by dapetcu21** [comment]
I just noticed that my calendar subscriptions in Apple Calendar wouldn't work anymore:
<img width="372" alt="Screen Shot 2021-05-02 at 22 25 57" src="https://user-images.githubusercontent.com/428060/116824958-7c5eda80-ab95-11eb-84df-aafdcb2a0bba.png">

So I tried going to the iCal link manually (https://eventcal.flown.io/?base64=true&calendar=MYCALENDARKEY&status=ACCEPTED) in Safari on macOS and got the above page (which is obviously not a valid .ical file). cURL-ing the link results in the same page.

**Comment by simonbengtsson** [comment]
Could you try getting a new url from the facebook event page and see if that works?

**Comment by dapetcu21** [comment]
I did. It didn't make a difference.

**Comment by arxeiss** [comment]
Is it possible that getting the link to ical export is not possible in my country? Can you share the screen where you can get the export link?

**Comment by dapetcu21** [comment]
https://www.facebook.com/events/calendar

You have a blue button in the top-right:
<img width="181" alt="Screen Shot 2021-05-13 at 12 50 27" src="https://user-images.githubusercontent.com/428060/118109388-cba0d880-b3e9-11eb-86a0-c12995cb635b.png">

**Comment by arxeiss** [comment]
You are right... Not sure what was wrong, because visiting the link redirected me to different page. But I was able to find it. 

P.S. I'm able to download it without login. In incognito mode I was able to download it as well

**Comment by dapetcu21** [comment]
Hmm... You're right. I can download it without login as well, but it still won't work in eventcal.

**Comment by simonbengtsson** [comment]
Is still an issue?

**Comment by hmijail** [comment]
When I press that FB "Add to Calendar" button it shows me a page saying "Sorry, this content isn't available right now". The URL itself does the same. With curl I get a 208KB HTML page, no iCal.
So I guess it is still an issue.

**Comment by simonbengtsson** [comment]
Clicking that button should download an ics file. Tried it now and this is the behavior for me both in normal and incognito mode. Note that it seems it only works on desktop browsers.

If there is no publicly accessible `ics` file is not much Eventcal can do. It is most likely some kind of region specific limitation on Facebook. I'll close this issue for now but if there is any ideas towards what can be done to solve this within Eventcal feel free to comment.
