### ISSUE TITLE
Utility does not work anymore

### ISSUE THREAD

**Issue by arxeiss** [simonbengtsson/eventcal#42]
I noticed events are not shown in Google Calendar anymore.
If I put into Google Calendar link from FB directly, it works. But when I put there link from eventcal, nothing works.

I would like to debug it, however I don't know how. Because I cannot fetch `webcal://` schema and if I replace it with `http` or `https` it download the index page.

**Comment by simonbengtsson** [comment]
Interesting! That you get the index page when changing to http or https could be the issue in itself since this utility only sends a normal GET request to facebook similar to when you go to the https/http url.

**Comment by arxeiss** [comment]
I'm not sure you are doing something. Or I did it differently before.
But now if I take generated link from eventcal and I change webcal:// to https it redirects me to Facebook and I see this:

![image](https://user-images.githubusercontent.com/5103109/145395546-83f6b4e7-0b65-4689-984d-a05480d73c97.png)

**Comment by simonbengtsson** [comment]
Rewrote service in nodejs and moved to google as hosting provider so should work now! If not let me know.

**Comment by simonbengtsson** [comment]
Rewrote service in nodejs and moved to google as hosting provider so should work now! If not let me know.

**Comment by arxeiss** [comment]
Thanks, I removed my Facebook account meanwhile :laughing: cannot test anymore
