### ISSUE TITLE
Error when adding to macOs system calendar

### ISSUE THREAD

**Issue by Startouf** [simonbengtsson/eventcal#43]
![Screenshot 2022-06-04 at 14 16 48](https://user-images.githubusercontent.com/7388889/171998578-f2ae0818-ffc7-460d-8f4b-d145c445ee5b.png)

Do you know where to find the error logs ?

**Comment by simonbengtsson** [comment]
Could you try again to see if this is still an issue? I tried now and it worked for my calendar. Likely it is a specific event in your calendar that breaks it.

**Comment by simonbengtsson** [comment]
Rewrote the service in nodejs and should work now. If not let me know.
