### ISSUE TITLE
Cancelled events visible and unable to decline

### ISSUE THREAD

**Issue by mateuszjablonski** [simonbengtsson/eventcal#44]
Everytime an event is cancelled, there is no option on Facebook to "opt out" from it, and therefore there is no way to remove the event from the calendar. Any idea how to solve this one?

**Comment by mateuszjablonski** [comment]
Follow-up: I fetched ICS files for both active and cancelled event, compared them, and there is no difference between them, so it is probably impossible to differentiate.

**Comment by simonbengtsson** [comment]
😞

**Comment by simonbengtsson** [comment]
Closing for now since likely out of scope of this service as mentioned in previous comment.
