### ISSUE TITLE
Utility doesn't seem to work anymore due to facebook changes

### ISSUE THREAD

**Issue by lopisok** [simonbengtsson/eventcal#45]
It worked smoothly for a long time but now it seems like facebook changed the way it works.
The description to get the url for upcoming events is not working anymore (right clicking impossible).
Also downloading an individual event and looking at the code doesn't reveal a uid & key.
Is it still working for you?

**Comment by lopisok** [comment]
Aha the save link button still works on the general page
https://www.facebook.com/events/calendar

**Comment by muscarina** [comment]
lopisok, having a hard time finding that "save link" button on the general page. Is it still there?

**Comment by lopisok** [comment]
@muscarina if you go to https://www.facebook.com/events/calendar you can see the "add to calendar" button. Right click and copy link address

@simonbengtsson I think the layout changed. When you click events as indicated in the guide it doesn't give an "add to calendar" button. It leads to "https://www.facebook.com/events?source=46&action_history=null" which is a short summary of  events.
But using the general calendar link: https://www.facebook.com/events/calendar works to get the link with uid & key.
 
However, when I use the link with your script https://eventcal.flown.io/ and add the link to google calendar, my facebook events are not showing up. So not sure if something is broken.

**Comment by simonbengtsson** [comment]
For me the guide at [https://eventcal.flown.io](https://eventcal.flown.io) still works. The page [https://www.facebook.com/events/calendar](https://www.facebook.com/events/calendar) has a "Add to Calendar" button and I get a calendar url when clicking the "Save Link" from the right click menu of this button. It doesn't look like this for you?

<img width="1432" alt="Screen Shot 2022-10-18 at 12 46 44" src="https://user-images.githubusercontent.com/3586691/196410125-aff50932-da78-4335-b33b-8ad3d70186ec.png">

**Comment by lopisok** [comment]
I also see this. However when copying the link address and using https://eventcal.flown.io/ to generate the webcal link, the events don't show in google calendar after adding the agenda. Also after giving it 12 hours to sync.
So not sure what's happening there.

**Comment by tellemstevedave** [comment]
Not working for me either. Did it yesterday over 12 hours ago

**Comment by simonbengtsson** [comment]
Got an error when I tried as well. In theory it should still be able to make it work however. I'll take a look 👍

**Comment by simonbengtsson** [comment]
Seems like the IP of the Digital Ocean droplet was blocked by Facebook. The script was still working well locally however. Migrated the service to nodejs now and changed hosting provider to Google which hopefully will not be blocked anytime soon. 

Could you verify it is working for you now?

**Comment by simonbengtsson** [comment]
Seems like the IP of the Digital Ocean droplet was blocked by Facebook. The script was still working well locally however. Migrated the service to nodejs now and changed hosting provider to Google which hopefully will not be blocked anytime soon. 

Could you verify it is working for you now?

**Comment by lopisok** [comment]
> 

Works perfectly again here! Tnx I missed this! :)
