### ISSUE TITLE
THANK YOU!!!

### ISSUE THREAD

**Issue by shirazd** [simonbengtsson/eventcal#5]
Simon,

I found your service after a post you made on Quora. Ever since the konscript freedom service went down (after a Facebook API change), I have sorely needed this. There's an Android app that will sync filtered Facebook events with your gcal but only works on the given device, leaving the laptop's calendar empty of any FB events. 

So a hearty thank you for hosting this service and big bonus points for sharing the code on github. I don't need to run my own service for now because the code you have it works great, and the service is working too. On that note, I think you have a marketable service here. It's interesting to me how hard it was to find this after some time and various google searches. If you publicize this a bit with a standalone (non-github) page describing your service, I think you actually have a product which you could charge users a couple bucks a year for, enough that would cover the hosting costs, I would think. (doesn't appear to be a big server hit). Just a thought!

Thanks again,
Shiraz

**Comment by simonbengtsson** [comment]
I'm glad you found it useful! And I agree, it's not easy to find as it is now. I should definitely do some seo of the website. Do you have any suggestions for what people might search for when they want to find it? 

The server costs are not an issue as I host a lot of other websites on my server so I will probably always keep it free and open source. But an interesting idea! I have thought of adding more features (started with some new features described in #4). To make the project a little bit bigger in scope though I might create a general ical filter service to filter any kind of calendar before it goes in google calendar. Can think of a few use cases would be handy.

**Comment by jwmann** [comment]
https://tapiriik.com/ has a similar kind of service.
He charges I think it was $2 for the year and I did it in a heartbeat.
Very useful.

Worth checking it out for some ideas 😄
