### ISSUE TITLE
Tried adding the calendar to google calendar and it did not work

### ISSUE THREAD

**Issue by tgifryday** [simonbengtsson/eventcal#6]
- No facebook events are showing up
- The failing event looks like this:

```
BEGIN:VCALENDAR
PRODID:Eventcal
VERSION:2.0
BEGIN:VEVENT
ORGANIZER;CN=Test"Test:MAILTO:example@example.com
DTSTART:20160901T120000Z
DTEND:20160903T190000Z
SUMMARY:Test
DESCRIPTION:Test
END:VEVENT
END:VCALENDAR
```

**Comment by simonbengtsson** [comment]
It actually seems to be a bug with Google Calendar ([more info](https://productforums.google.com/forum/#!topic/calendar/VLUF7s2boqo;context-place=forum/calendar)).

That said, I'll see if I can work around the issue somehow. I'll write here once I have looked into it.

Btw, replaced your private calendar with an example event with the same problem.

**Comment by simonbengtsson** [comment]
Manually escapes the organizer field now and removes any quotes from it now.
