### ISSUE TITLE
'maybe' events not showing

### ISSUE THREAD

**Issue by Yo-L** [simonbengtsson/eventcal#7]
Hi,
Thanks a lot for building this! I've used Sunrise calendar for a long time, which had awesome Google calendar and Facebook events integration. Since they're pulling the plug I'm looking for alternatives, this seems great.

I got my 'attending' Facebook events to show up, but my 'maybe' events don't show, even though I selected it and it says status=ACCEPTED,TENTATIVE in the URL. 
When I only select 'not responded to', I get all my 'maybe' events to show as well as my 'not responded to' events.

Is there anything I have to do differently? Thanks in advance!

**Comment by MrHappytime** [comment]
I have also run into this issue. Changing 'TENTATIVE' to 'INTERESTED' or 'MAYBE' did not help either. Is there a different value needed for this?

**Comment by Yo-L** [comment]
Somehow the issue resolved itself for me after a day or so. I have no idea what happened, bu now I have three beautiful different calendars in Google that I can turn on and of and have different colors: One 'attending', one 'interested', one 'invited'.

**Comment by MrHappytime** [comment]
That's a great idea! What values did you use for the status on the calendars? Since i can't get TENTATIVE to work...

**Comment by Yo-L** [comment]
The other two worked instantly for me, the 'tentative' events didn't appear so I gave up after posting here. Then when I came back to it later (one day or a few days or so) they where there. Have you given it some time? Maybe they need more 'processing time'. I read somewhere that some external Google Calenders you add refresh / pull data only once a day.

The url just ends with `&status=TENTATIVE`
`

**Comment by MrHappytime** [comment]
I set it up yesterday morning. I'll set up separate calendars today and see what happens coming days; see what happens. Thanks!

**Comment by simonbengtsson** [comment]
I'm on holiday at the moment and forgot to renew the domain. Will do that tomorrow and it should be up and running again.

**Comment by MrHappytime** [comment]
Tested and it's all working now! Thanks a lot! This is great; now i can finally organize my life :)
