### ISSUE TITLE
Chrome strips an & from query string causing errors for some users

### ISSUE THREAD

**Issue by shamilovtim** [simonbengtsson/eventcal#9]
Initially could not get the calendar to load. Would hit a 'cannot fetch URL' error in G-Cal. I did a bit of troubleshooting and attempted to add it to my subscribed calendars once again.

1. Events that were Accepted and Tentative were already selected on the site.
2. Copied my FB webcal URL by clicking on "Upcoming Events" link in FB. This pulled up a chrome popup that had the webcal URL in the field.
3. Pasted my fb webcal URL into the input: Facebook Calendar input box. 
4. Copied the returned URL of eventcal.flown.io/[...] into my gmail subscribed calendars.

I received an error "cannot fetch URL" from Gmail.

I again attempted this but this time I used "copy link URL" in Chrome on the "Upcoming Events" link. Rest of the steps were the same. This time it synced. I ran a diff on the two urls. First side: clicking the link in chrome, second time: copying the source link from Chrome. Turns out that chrome strips a & from the key parameter on the query string. See the following:

webcal://www.facebook.com/ical/u.php?uid=12345&key=ABCDEFG

webcal://www.facebook.com/ical/u.php?uid=12345key=ABCDEFG

This affected the returned query string by stripping the == operator before &status. 

In case this affects users in the future I suggest checking for the stripped & on the query string and correcting it automatically on the return URL.

**Comment by shamilovtim** [comment]
So here's an update. I did a bit of troubleshooting and attempted to add it to my subscribed calendars once again.

1. Events that were Accepted and Tentative were already selected on the site.
2. Copied my FB webcal URL by clicking on "Upcoming Events" link in FB. This pulled up a chrome popup that had the webcal URL in the field.
3. Pasted my fb webcal URL into the input: Facebook Calendar input box. 
4. Copied the returned URL of eventcal.flown.io/[...] into my gmail subscribed calendars.

I received an error "cannot fetch URL" from Gmail.

I again attempted this but this time I used "copy link URL" in Chrome on the "Upcoming Events" link. Rest of the steps were the same. This time it synced. I ran a diff on the two urls. First side: clicking the link in chrome, second time: copying the source link from Chrome. Turns out that chrome strips a & from the key parameter on the query string. See the following:

webcal://www.facebook.com/ical/u.php?uid=12345&key=ABCDEFG

webcal://www.facebook.com/ical/u.php?uid=12345key=ABCDEFG

This affected the returned query string by stripping the == operator before &status. 

webcal://eventcal.flown.io?base64=true&calendar=d2ViY2FsOi8vd3d3LmZhY2Vib29rLmNvbS9pY2FsL3UucGhwP3VpZD0yMjQyNjEwNyZrZXk9QVFDMUp1TF8yT3UtbndRSg==&status=ACCEPTED,TENTATIVE

To keep from wasting user's time in the future, I suggest checking for the stripped & on the query string and correcting it automatically on the return URL.

**Comment by simonbengtsson** [comment]
What operating system are you running and what is your default calendar application? If I remember correctly the link opens iCalendar on macOS which I think do work. Will try it again later today.

**Comment by shamilovtim** [comment]
OSX, see screenshot where it trims an & from the query string.

https://gyazo.com/c31853bc074dc4b5c99d4f8962100387

**Comment by simonbengtsson** [comment]
Added the ampersand if it is missing now. Let me know if it works for you!
